# Generated by Django 4.2.2 on 2023-06-17 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_entity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adventure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point_longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('starting_point_latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('destination_longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('destination_latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('points_earned', models.PositiveSmallIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PointOfInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=12)),
                ('order', models.SmallIntegerField(default=0)),
                ('visited', models.BooleanField(default=False)),
                ('story', models.TextField()),
                ('adventure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_of_interest', to='core.adventure')),
            ],
        ),
        migrations.DeleteModel(
            name='Entity',
        ),
    ]
