# Generated by Django 4.2.2 on 2023-06-18 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_chatconversation_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pointofinterest",
            name="place_id",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="pointofinterest",
            name="adventure",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="points_of_interest",
                to="core.adventure",
            ),
        ),
    ]
