# Generated by Django 4.2.2 on 2023-06-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatconversation_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointofinterest',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
    ]
